hosts/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from hosts.views import HostViewSet, play_book,ad_hoc


router = routers.DefaultRouter()
router.register(r'hosts', HostViewSet)
# router.register(r'host', HostloginViewSet)


urlpatterns = [
    url(r'', include(router.urls)),
    url(r'^playbook/', play_book, name='play_book'),
    url(r'adhoc/', ad_hoc, name='ad_hoc'),


]

users/urls.py
from django.conf.urls import url, include
from users.views import *
from rest_framework import routers


router = routers.DefaultRouter()
router.register('login', UserTokenViewSet)
router.register('register', UsersViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),

    url(r'^userlogin/$', UserloginViewSite, name='login'),
    url(r'^userlogout/$', UserlogoutViewSite, name='logout'),
    url(r'^usermake/$', UsermakeViewSite, name='nake'),
    url(r'^addapp/', CaddappViewSite, name='addapp'),
    url(r'^putermage', CmageViewSite, name='putermage'),
    url(r'^remotquery', CremoteViewSite, name='remotquery'),
    url(r'^useraddputer/', UseraddcmpViewSite, name='addputer'),
    url(r'^index/$', UserindexViewSite, name='index'),
]

yunwei/urls.py
from django.contrib.staticfiles import views
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.documentation import include_docs_urls
from rest_framework_jwt.views import obtain_jwt_token


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'^users/', include('users.urls', namespace='user')),
    # url(r'^', include('hosts.urls')),
    url(r'^docs/', include_docs_urls(title='p1805官网文档')),
    url(r'^api-token-auth/', obtain_jwt_token),
    url(r'^static/(?P<path>.*)$', views.serve),
    url(r'^hosts/', include('hosts.urls')),
]

templates/C-RemoteQuery.html
<!DOCTYPE html>
<html lang="en">

	<head>
        {% load static %}
		<meta charset="utf-8">
		<title>TiMi</title>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
		<!-- Demo css -->
		<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
		<link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
		<!--Link Swiper's CSS-->
		<link rel="stylesheet" href="{% static "css/swiper-3.4.2.min.css" %}">
		<!--styles-->
		<link rel="stylesheet" href="{% static "css/swiper-menu.css" %}">
		<link rel="stylesheet" href="{% static "css/autoop-index.css" %}">

		<!-- 动态加载 -->
		<link rel="stylesheet" href="{% static "css/autoop-zkym.css" %}">
		<link rel="stylesheet" type="text/css" href="{% static "css/C-S-in.css" %}"/>
		<link rel="stylesheet" type="text/css" href="{% static "css/all-page.css" %}"/>
		<link rel="stylesheet" type="text/css" href="{% static "css/C-add-this.css" %}"/>

	</head>

	<body background="{% static "img/background.jpg" %}">

		<!-- modal-overlay -->

		<div class="modal-alert">
			<h4></h4>
		</div>

		<!-- Swiper -->
		<div class="swiper-container">
			<div class="swiper-wrapper">

				<div class="swiper-slide menu">

					<div class="index-menu col-sm-9 col-xs-11">
						<div class="index-menu-home">
							<a href="{% url 'user:index' %}">
								<h1>TiMi</h1></a>
						</div>
						<ul class="index-menu-nav">
							<li>
								<a href="{% url 'user:index' %}">
									<!--<span class="first fa fa-laptop"></span>-->
									<span class="first fa fa-cny"></span>
									<span class="text">用户信息</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="{% url 'user:addputer' %}">
									<span class="first fa fa-bar-chart"></span>
									<span class="text">添加主机</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="{% url 'user:addapp' %}">
									<span class="first fa fa-cny"></span>
									<span class="text">部署管理</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="{% url 'user:putermage' %}">
									<span class="first fa fa-sitemap"></span>
									<span class="text">主机信息</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li id="active">
								<a href="{% url 'user:remotquery' %}">
									<span class="first fa fa-dashboard"></span>
									<span class="text">远程查询</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<!--<li>
								<a href="">
									<span class="first fa fa-book"></span>
									<span class="text"></span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="">
									<span class="first fa fa-book"></span>
									<span class="text"></span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>-->
						</ul>
					</div>

				</div>


            <div class="content">
                <div class=" col-sm-12 col-xs-12">
                    <div class="index-main-top">
                        <div class="menu-button">
                            <div class="bar"></div>
                            <div class="bar"></div>
                            <div class="bar"></div>
                        </div>
                        <h2 class="index-main-top-nav">TiMi&emsp;<i class="fa fa-angle-right"></i>&emsp;<span>远程查询</span></h2>
                        <div class="index-main-top-signout">
                            {% if request.user.id %}
                                <span>欢迎您：{{ request.user.username }}</span>
                                <div style="float: right">
                                    <a href="{% url 'user:logout' %}"><span>注销</span ></a>
                                </div>
                            {% else %}
                                 <a href="{% url 'user:login' %}"><span class="fa">&#xf007;&emsp;</span>登陆</a>
                            {% endif %}
                        </div>
                    </div>
                    <div class="index-main-contain my-back">

                        <!-- contain -->
                        <div class="">
                            <div class="" style="width: auto;">
                            	<h3>尊敬的 <span>10.2.0.33</span>您好</h3>
                            </div>
                            <form action="" id="form-flot" style="">
                                {% csrf_token %}
								<div class="forn-st"  style="">
									<div class="title-do" style="font-size: 25px;">可查询主机:</div>
									<div class=" col-md-10 form-for" id="us-id">

									</div>
								</div>
								<!-- 动态加载部署软件/部署文件 -->
								<!-- 部署软件 -->
								<div class="forn-st" style="">
									<div class="title-do">查询命令:</div>
									<div class=" col-md-10 form-for" id="us-app">
											<input id="form-query" type="text" name="install" class="install" value="" />
									</div>
								</div>
								 <!--./动态加载部署软件/部署文件 ->-->
								<input type="button" value="确认查询" id="sut-add"/>
							</form>
							<div class="part-1">
								<div class="" id="retur"><b>返回结果:</b></div>
								 <textarea id="retur-mage" style="overflow: auto">

                                 </textarea>
							</div>
                        </div>
                        <!-- /contain -->

                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Swiper JS -->
    <script src="{% static "js/swiper-3.4.2.min.js" %}"></script>
    <!-- js -->
    <script src="{% static "js/jquery-2.2.3.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript">
    	$(function(){
    	$.ajax({
                type: "get",
                dataType:"json",
                url: "/hosts/hosts/",
　　　　　　　　　 success: function(data){//返回的参数就是 action里面所有的有get和set方法的参数
                    console.log(data);
                    for (i=0; i<data.length;i++){
                         $('#us-id').append('<div><input type="checkbox" name="host" class="host" ' +
                             'value="'+data[i].hostip+'" /><div class="sp-na">'+data[i].hostip+'</div></div>')
                    }

                }
            })
    	});
    	host=[];
        install=[];
        $('#sut-add').click(function () {
            host_checked = $("input[name='host']:checked").each(function () {
                host.push($(this).val())
            });
            csrf=$("input[name='csrfmiddlewaretoken']").val();
            params={"host":host,"module_args":$('#form-query').val(),"csrfmiddlewaretoken":csrf};

            $.post('/hosts/adhoc/',params,function (data) {
                $('#retur-mage').text(JSON.stringify(data));
            },"json");
        })
    </script>
</body>
</html>

templates/C-add-this.html
<!DOCTYPE html>
<html lang="en">
    <head>

	    {% load static %}
		<meta charset="utf-8">
		<title>TiMi</title>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
		<!-- Demo css -->
		<link rel="stylesheet" href="{% static "css/bootstrap.min.css"  %}">
		<link rel="stylesheet" href="{% static "css/font-awesome.min.css"  %}">
		<!--Link Swiper's CSS-->
		<link rel="stylesheet" href="{% static "css/swiper-3.4.2.min.css"  %}">
		<!--styles-->
		<link rel="stylesheet" href="{% static "css/swiper-menu.css"  %}">
		<link rel="stylesheet" href="{% static "css/autoop-index.css"  %}">
		<link rel="stylesheet" type="text/css" href="{% static "css/back-img.css"  %}" />

		<!-- 动态加载 -->
		<link rel="stylesheet" href="{% static "css/autoop-zkym.css"  %}">
		<link rel="stylesheet" type="text/css" href="{% static "css/C-add-this.css"  %}"/>
	</head>

	<body background="{% static "img/background.jpg" %}">


		<!-- modal-overlay -->

		<div class="modal-alert">
			<h4></h4>
		</div>

		<!-- Swiper -->
		<div class="swiper-container">
			<div class="swiper-wrapper">

				<div class="swiper-slide menu">

					<div class="index-menu col-sm-9 col-xs-11">
						<div class="index-menu-home">
							<a href="{% url 'user:index' %}">
								<h1>TiMi</h1></a>
						</div>
						<ul class="index-menu-nav">
							<li>
								<a href="{% url 'user:index' %}">
									<span class="first fa fa-laptop"></span>
									<span class="text">用户信息</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="{% url 'user:addputer' %}">
									<span class="first fa fa-cny"></span>
									<span class="text">添加主机</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li id="active">
								<a href="{% url 'user:addapp' %}">
									<span class="first fa fa-cny"></span>
									<span class="text">部署管理</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="{% url 'user:putermage' %}">
									<span class="first fa fa-sitemap"></span>
									<span class="text">主机信息</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="{% url 'user:remotquery' %}">
									<span class="first fa fa-dashboard"></span>
									<span class="text">远程查询</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<!--<li>
								<a href="">
									<span class="first fa fa-book"></span>
									<span class="text"></span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="">
									<span class="first fa fa-book"></span>
									<span class="text"></span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>-->
						</ul>
					</div>

				</div>

				<div class="content">
					<div class=" col-sm-12 col-xs-12">
						<div class="index-main-top">
							<div class="menu-button">
								<div class="bar"></div>
								<div class="bar"></div>
								<div class="bar"></div>
							</div>
							<h2 class="index-main-top-nav">TiMi&emsp;<i class="fa fa-angle-right"></i>&emsp;<span>一键安装</span></h2>
							<div class="index-main-top-signout">
								{% if request.user.id %}
                                    <span>欢迎您：{{ request.user.username }}</span>
                                    <div style="float: right">
                                        <a href="{% url 'user:logout' %}"><span>注销</span ></a>
                                    </div>
                                {% else %}
                                     <a href="{% url 'user:login' %}"><span class="fa">&#xf007;&emsp;</span>登陆</a>
                                {% endif %}
							</div>
						</div>
						<div class="index-main-contain" style="background: blanchedalmond;">

							<!-- contain -->
							<div class="">
								<div class="" style="width: auto;">
									<h3>尊敬的: <span>{{ request.user.username }}
                            		
                            	</span>请选择你的安装</h3>
								</div>

									<div class="index-main-contain">										
									<!-- header -->
											<div class="contain-header">
												<h3><b>部署管理</b></h3>
											</div>
												<!-- 目标主机 -->
												<form id="form-flot" style="">
													{% csrf_token %}
                                                    <div class="forn-st"  style="">
														<div class="title-do">目标主机:</div>
														<div class=" col-md-10 form-for" id="us-id">

                                                        </div>
													</div>
													<!-- 动态加载部署软件/部署文件 -->
													<!-- 部署软件 -->
													<div class="forn-st" style="">
														<div class="title-do">选择软件:</div>
														<div class=" col-md-10 form-for" id="us-app">
																<input type="checkbox" name="install" class="install" value="nginx" /><div class="sp-na">nginx</div>
																<input type="checkbox" name="install" class="install" value="php" /><div class="sp-na">php</div>
																<input type="checkbox" name="install" class="install" value="ping" /><div class="sp-na">ping</div>
														</div>
													</div>
													 <!--./动态加载部署软件/部署文件 ->-->
													<input type="button" value="确认安装" id="sut-add"/>
												</form>
												<div class="part-1">
													<div class="" id="retur"><b>返回结果:</b></div>
{#													<div  class="" id="retur-mage">#}
                                                        <textarea id="retur-mage" style="overflow: auto" >
                                                        </textarea>
{#													</div>#}
												</div>
										</div>
										 <!--/contain--> 
							</div>
							<!-- /contain -->

						</div>
					</div>
				</div>
			</div>
		</div>

		<!-- Swiper JS -->
		<script src="{% static "js/swiper-3.4.2.min.js"  %}"></script>
		<!-- js -->
		<script src="{% static "js/jquery-2.2.3.min.js"  %}"></script>
		<script src="{% static "js/bootstrap.min.js"  %}"></script>
		<script type="text/javascript">
			$(function(){
                $.ajax({
                type: "get",
                dataType:"json",
                url: "/hosts/hosts/",
　　　　　　　　　 success: function(data){//返回的参数就是 action里面所有的有get和set方法的参数
                    console.log(data);
                    for (i=0; i<data.length;i++){
                         $('#us-id').append('<div><input type="checkbox" name="host" class="host" ' +
                             'value="'+data[i].hostip+'" /><div class="sp-na">'+data[i].hostip+'</div></div>')
                    }

                }
            })

		    });
			host=[];
			install=[];
            $('#sut-add').click(function () {
                host_checked = $("input[name='host']:checked").each(function () {
                    host.push($(this).val())
                });
                install_checked = $("input[name='install']:checked").each(function () {
                    install.push($(this).val())
                });
                csrf=$("input[name='csrfmiddlewaretoken']").val();
                params={"host":host,"install":install,"csrfmiddlewaretoken":csrf};

                $.post('/hosts/playbook/',params,function (data) {
                    {#alert(JSON.stringify(data));#}
                    {#console.log(data)#}
                    {#console.log(JSON.parse(data))#}
                    $('#retur-mage').text(JSON.stringify(data));

                    {#$('#retur-mage').html(data)#}



                },"json");
            })
			
		</script>

	</body>

</html>

templates/user-add-C.html
<!DOCTYPE html>
<html lang="en">

	<head>
        {% load static %}
		<meta charset="utf-8">
		<title>TiMi</title>
		<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
		<!-- Demo css -->
		<link rel="stylesheet" href="{% static "css/bootstrap.min.css"  %}">
		<link rel="stylesheet" href="{% static "css/font-awesome.min.css"  %}">
		<!--Link Swiper's CSS-->
		<link rel="stylesheet" href="{% static "css/swiper-3.4.2.min.css"  %}">
		<!--styles-->
		<link rel="stylesheet" href="{% static "css/swiper-menu.css"  %}">
		<link rel="stylesheet" href="{% static "css/autoop-index.css"  %}">

		<!-- 动态加载 -->
		<link rel="stylesheet" href="{% static "css/autoop-zkym.css"  %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/C-add-this.css" %}"/>
		<!--<link rel="stylesheet" type="text/css" href="css/all-page.css"/>-->

	</head>

	<body background={% static "img/background.jpg" %}>
    {% csrf_token %}

		<!-- modal-overlay -->

		<div class="modal-alert">
			<h4></h4>
		</div>

		<!-- Swiper -->
		<div class="swiper-container">
			<div class="swiper-wrapper">

				<div class="swiper-slide menu">

					<div class="index-menu col-sm-9 col-xs-11">
						<div class="index-menu-home">
							<a href="{% url 'user:index' %}">
								<h1>TiMi</h1></a>
						</div>
						<ul class="index-menu-nav">
							<li>
								<a href="{% url 'user:index' %}">
									<!--<span class="first fa fa-laptop"></span>-->
									<span class="first fa fa-cny"></span>
									<span class="text">用户信息</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li id="active">
								<a href="{% url 'user:addputer' %}">
									<span class="first fa fa-bar-chart"></span>
									<span class="text">添加主机</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="{% url 'user:addapp' %}">
									<span class="first fa fa-cny"></span>
									<span class="text">部署管理</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="{% url 'user:putermage' %}">
									<span class="first fa fa-sitemap"></span>
									<span class="text">主机信息</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="{% url 'user:remotquery' %}">
									<span class="first fa fa-dashboard"></span>
									<span class="text">远程查询</span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<!--<li>
								<a href="">
									<span class="first fa fa-book"></span>
									<span class="text"></span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
							<li>
								<a href="">
									<span class="first fa fa-book"></span>
									<span class="text"></span>
									<span class="card">
                                    <i class="front fa fa-angle-left"></i>
                                    <i class="back"></i>
                                </span>
								</a>
							</li>
						</ul>-->
                        </ul>
                    </div>
				</div>

                    <div class="content">
                        <div class=" col-sm-12 col-xs-12">
                            <div class="index-main-top">
                                <div class="menu-button">
                                    <div class="bar"></div>
                                    <div class="bar"></div>
                                    <div class="bar"></div>
                                </div>
                                <h2 class="index-main-top-nav">TiMi&emsp;<i class="fa fa-angle-right"></i>&emsp;<span>添加电脑</span></h2>
                                <div class="index-main-top-signout">
                                    {% if request.user.id %}
                                        <span>欢迎您：{{ request.user.username }}</span>
                                        <div style="float: right">
                                            <a href="{% url 'user:logout' %}"><span>注销</span ></a>
                                        </div>
                                    {% else %}
                                         <a href="{% url 'user:login' %}"><span class="fa">&#xf007;&emsp;</span>登陆</a>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="index-main-contain my-back">

                                <div class="modal-data active add-log" style="display: block;">

                                    <div class="modal-head">
                                        <h3>请提信息</h3>
                                    </div>
                                    <hr>
                                    <form action="" class="modal-form" >
                                            <div class="form-group">
                                                <label for="inputIP" class="col-sm-2 control-label">hostip：</label>
                                                <div class="col-sm-10">
                                                    <input name="hostip" type="IP" class="form-control" id="hostip" required="required" placeholder="hostip">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputhostname" class="col-sm-2 control-label">port：</label>
                                                <div class="col-sm-10">
                                                    <input name="port" type="hostname" class="form-control" id="port" required="required" placeholder="port">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputproduct" class="col-sm-2 control-label">username：</label>
                                                <div class="col-sm-10">
                                                    <input name="username" type="product" class="form-control" id="username" required="required" placeholder="username">
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <label for="inputapplication" class="col-sm-2 control-label">password：</label>
                                                <div class="col-sm-10">
                                                    <input name="password" type="application" class="form-control" id="password1" required="required" placeholder="password">
                                                </div>
                                            </div>
                                            <div class="form-group" style="display: none">
                                                <label for="inputstatus" class="col-sm-2 control-label">hostname：</label>
                                                <div class="col-sm-10">
                                                    <input name="hostname" type="status" class="form-control" id="hostname" required="required" placeholder="hostname">
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <input class="btn reset" type="reset" value="重置">
                                                <button class="btn reset" id="but" type="submit">提交</button>
                                                <!--<input class="btn btn-info submit" id="but" type="button submit" value="提交">-->
                                            </div>
                                    </form>
                                    <div class="part-1">
                                        <div class="" id="retur"><b>返回结果:</b></div>
                                         <textarea id="retur-mage" style="overflow: auto" >

                                         </textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        </div>
                    </div>
		        </div>
            </div>
        </div>
		<!-- Swiper JS -->
		<script src="{% static "js/swiper-3.4.2.min.js"  %}"></script>
		<!-- js -->
		<script src="{% static "js/jquery-2.2.3.min.js"  %}"></script>
		<script type="text/javascript">
			$('#but').click(function(){
				hostip = $('#hostip').val();
				port = $('#port').val();
				username = $('#username').val();
				password1 = $('#password1').val();
				csrf=$("input[name='csrfmiddlewaretoken']").val()
				params ={"hostip":hostip,"port":port,"username":username, "password":password1,"hostname":hostip,"csrfmiddlewaretoken":csrf};
				console.log(params);

 //           });
				$.ajax({

					url:'/hosts/hosts/',
					type:'POST',
					dataType: 'json',
//					jsonpCallback:'fnBack',
			    	data:params

				})
				.done(function(data){
					console.log(data);
                     $('#retur-mage').text(JSON.stringify(data));
					alert('添加成功')

				})
				.fail(function(){
					alert('失败')
				})
			})
		</script>
	</body>

</html>